app.py
from flask import Flask, current_app
import OpenOPC


def create_app():
    # Funcao responsavel por inicializar a aplicacao REST
    app = Flask(__name__)
    app.threaded = False
    __register_blueprints(app)
    app.opc = OpenOPC.client()

    return app


def __register_blueprints(app):
    from views.api import blueprint
    from views.star_delta_visualization import blueprint as star_delta_blueprint


    app.register_blueprint(blueprint) # Registra na aplicacao os endpoints definidos no arquivo api.py
    app.register_blueprint(star_delta_blueprint) # Registra na aplicacao os endpoints definidos no arquivo star_delta.py


def get_opc_connected_instance(server):
    # Funcao auxiliar que retorna uma instancia do cliente OpenOPC conectada no servidor passado no argumento
    opc = current_app.opc
    opc.connect(server)

    return opc

views/api.py
from flask import Blueprint, request, current_app, jsonify

from app import get_opc_connected_instance

blueprint = Blueprint('api', __name__, url_prefix='/api')


@blueprint.route('/servers', methods=['GET'])
def get_servers():
    opc = current_app.opc

    return jsonify(opc.servers()) # Retorna a lista de servidores


@blueprint.route('/<server>/info', methods=['GET'])
def get_server_info(server):
    opc = get_opc_connected_instance(server=server) # Conecta no servidor escolhido

    return {info[0]: info[1] for info in opc.info()} # Retorna as infomacoes do servidor formatadas como um dicionario


@blueprint.route('/<server>/items', methods=['GET'])
def get_items(server):
    opc = get_opc_connected_instance(server=server)

    items = opc.read(opc.list(recursive=True)) # Consulta a lista de todos os itens do servidor e realiza a leitura de todos os valores

    return {item[0]: item[1:] for item in items} # Retorna os nomes e valores de todos os itens formatados como um dicionario


@blueprint.route('/<server>/item/<item_name>', methods=['GET'])
def get_single_item(server, item_name):
    opc = get_opc_connected_instance(server=server)

    item = {item_name: opc.read(item_name)} # Realiza a leitura do valor do item escolhido e formata como dicionario

    return item # Retorna o nome e valor do item escolhido



@blueprint.route('/<server>/items', methods=['POST'])
def post_items_value(server):
    opc = get_opc_connected_instance(server)
    data = request.json # Recupera as infomarcoes enviadas no corpo da requisicao

    for key, value in data.items(): # Itera sobre cada items recebido no compro da requisicao
        opc[key] = value # Atribui o valor desejado ao item informado

    items = opc.read(data.keys()) # Realiza a leitura dos itens para os quais foram atribruidos novos valores

    return {item[0]: item[1:] for item in items} # Retorna os nomes e valores dos items modificados

views/star_delta_visualization.py
from flask import Blueprint, request, render_template


blueprint = Blueprint('star-delta-visualization', __name__, url_prefix='/star-delta')


@blueprint.route('/', methods=['GET'])
def star_delta_visualization():
    return render_template("star_delta_view.html") # Exibe a pagina web do arquivo star_delta_view.html

templates/star_delta_view.html
<!DOCTYPE html>
<html>
    <head>
        <style type="text/css">
            body {
                font-family: "Courier New", sans-serif;
                box-sizing: border-box;
            }
            .buttons {
                font-size: 4em;
            }
            .dot {
                height: 25px;
                width: 25px;
                background-color: #bbb;
                border-radius: 50%;
            }
            .box {
                width: 100px;
                height: 50px;
                border: 1px solid #000;
                display: inline-block;
            }
            .box-title{
                border-bottom: double;
                text-align: center;
                font-weight: bold;
            }
        </style>
    </head>
    <body>
        <div style="align-items: center; justify-content: center;">
            <div style="align-items: center; margin-top: 10px; margin-left: 20px; float: right;">
                <!-- Elemento do timer -->
                <div class="box">
                    <div class="box-title">Timer</div>
                    <div id= "timer" style="text-align: left;"></div>
                </div>
                <!-- Elemento do Relógio -->
                <div class="box">
                    <div class="box-title">Relógio</div>
                    <div id= "clock" style="text-align: center;"></div>
                </div>
            </div>
            <!-- Elemento do botao de liga e desliga -->
            <div class="buttons" style="width: min-content; display: inline-block;">
                <button id="on_off_button" type="button"></button>
            </div>
            <!-- Elemento do indicador de motor ligado -->
            <span class="dot" id="on_off_probe" style="display: inline-block;"></span>
            <!-- Caixa de texto do tempo de transicao do timer -->
            <form style="width: fit-content;">
                <div style="width: fit-content;">Valor do timer (s)</div>
                <input id="timerValue" value="" style="width: fit-content;"></input>
                <button id="updateTimerButton" style="width: fit-content;" onclick="updateTimerValue()">Atualizar</button>
            </form>
        </div>
        <!-- Elemento do diagrama da partida estrela-triangulo -->
        <div style="margin-left: 50px;">
            <object id="svgObject" data="{{url_for('static', filename='star_delta.svg')}}" type="image/svg+xml"></object>
        </div>
    <script>
        var button = document.getElementById("on_off_button");
        var request = new XMLHttpRequest();

        button.onclick = function(){
            // Realiza um POST no endpoint api/ProcessSimulator1.1/items no clique do botao de liga/desliga
            request.open("post", {{ url_for('api.post_items_value', server="ProcessSimulator1.1") | tojson }});
            request.setRequestHeader('Content-Type', 'application/json', false);
            // Atualiza o valor do item Connection1.INB0_0 por meio do POST
            // A variavel on_off_switch e uma variavel global com o ultimo estado do item Connection1.INB0_0
            if (on_off_switch){
                request.send(JSON.stringify({"Connection1.INB0_0": false}));
            } else{
                request.send(JSON.stringify({"Connection1.INB0_0": true}));
            }
        }

        function updateTimerValue(){
            // Realiza um POST no endpoint api/ProcessSimulator1.1/items no clique do botao de Atualizar
            timer_value = document.getElementById("timerValue");

            request.open("post", {{ url_for('api.post_items_value', server="ProcessSimulator1.1") | tojson }});
            request.setRequestHeader('Content-Type', 'application/json', false);
            // Atualiza o valor do item Connection1.MEMDW1 por meio do POST
            request.send(JSON.stringify({"Connection1.MEMDW1": timer_value.value*1000}));
        }

        window.onload = function(){
            // Redmensiona o diagrama de acorod 

            mySVG = document.getElementById("svgObject").contentDocument.getElementsByTagName('svg')[0];
            mySVG.setAttribute("viewBox", [0, 0, mySVG.getAttribute("width"), mySVG.getAttribute("height")].join(" "));

            mySVG.removeAttribute("width");
            mySVG.removeAttribute("height");

            refreshValues();
        }
        // Chama a funcao que realiza um GET no endpoint api/ProcessSimulator1.1/items e atualiza os elemento da pagina
        setInterval(refreshValues, 500);

        function refreshValues() {
            // Realiza um GET no endpoint api/ProcessSimulator1.1/items e atualiza os elemento da pagina
            var request = new XMLHttpRequest();
            request.onreadystatechange = function() {
                // Atualiza os elementos da pagina de acordo com o retorno do GET
                if (request.readyState == 4 && request.status == 200)
                    updateElements(JSON.parse(request.responseText))
            }
            // Realiza um GET no endpoint api/ProcessSimulator1.1/items
            request.open("get", {{ url_for('api.get_items', server="ProcessSimulator1.1") | tojson }});
            request.setRequestHeader('Content-Type', 'application/json', false);
            request.send(null);
        }

        function updateElements(json_response) {
            var switches_mapping = {
                "Connection1.OUTB0_1": mySVG.getElementById("star1"),
                "Connection1.OUTB0_2": mySVG.getElementById("star2"),
                "Connection1.OUTB0_3": mySVG.getElementById("star3"),
                "Connection1.OUTB0_4": mySVG.getElementById("delta1"),
                "Connection1.OUTB0_5": mySVG.getElementById("delta2"),
                "Connection1.OUTB0_6": mySVG.getElementById("delta3")
            };
            
            // Atualiza a posicao dos switches de acordo com o valor dos itens Connection1.OUTB0_1 ao 
            // Connection1.OUTB0_6
            for (var key in switches_mapping){
                if (json_response[key][0]){
                	removeRotation(switches_mapping[key]);
                } else{
                    rotateSwitch(switches_mapping[key]);
                }
            }
            
            // Atribui o valor do item Connection1.INB0_0 a uma variavel global
            on_off_switch = json_response["Connection1.INB0_0"][0];

            // Atualiza o texto do botao de liga/desliga de acordo com o valor do item Connection1.INB0_0
            setOnOffButtonText(on_off_switch);
            // Atualiza o contador do timer de acordo com o valor do item Connection1.OUTW1
            setTimerText(json_response["Connection1.OUTW1"][0]);
            // Atualiza a cor do indicador de acordo com o valor do item Connection1.OUTB0_0
            setProbeColor(json_response["Connection1.OUTB0_0"][0]);
            // Atualiza o valor do relogio de acordo com o valor do item Connection1.OUTDW3
            setClockText(json_response["Connection1.OUTDW3"][0]); 
            // Atualiza o texto da caixa de texto "Valor do timer" de acordo com valor do item Connection1.MEMDW1
            setTimerCurrentValue(json_response["Connection1.MEMDW1"][0])
        }

        function rotateSwitch(line) {
            var origin = line.getAttribute("d").substring(2).split(" ", 1);
            line.setAttribute("transform", `rotate(45 ${origin})`);
        }

        function removeRotation(line) {
            line.setAttribute("transform", "");
        }

        function setOnOffButtonText(switch_value){
            if (switch_value){
                button.textContent = "Desligar";
            } else {
                button.textContent = "Ligar";
            }
        }

        function setTimerText(timer_value){
            var timer = document.getElementById("timer");
            timer.textContent = `${timer_value/100}s`;
        }

        function setProbeColor(probe_value){
            var on_off_probe = document.getElementById("on_off_probe");
            if (probe_value){
                on_off_probe.style.backgroundColor = "green";
            } else{
                on_off_probe.style.backgroundColor = "red";
            }
        }

        function msToTime(ms) {
            // Obtem o tempo no formato HH:MM:SS a partir do valor total em mili segundos
            function pad(n) {
                return ('00' + n).slice(-2);
            }

            var hrs = Math.trunc(ms / 3600000);
            var mins_aux = ms % 3600000;
            var mins = Math.trunc(mins_aux / 60000);
            var secs_aux = mins_aux % 60000;
            var secs = Math.trunc(secs_aux / 1000);

            return pad(hrs) + ':' + pad(mins) + ':' + pad(secs)
        }

        function setClockText(clock_value){
            var clock = document.getElementById("clock");
            clock.textContent = `${msToTime(clock_value)}`;
        }

        function setTimerCurrentValue(timer_current_value){
            timer_value = document.getElementById("timerValue");
            update_button = document.getElementById("updateTimerButton");
            
            if (document.activeElement === timer_value || document.activeElement === update_button)
                return

            timer_value.value = timer_current_value / 1000;
        }
    </script>
    </body>
</html>